Algoritmo "melhor_escola"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Solicita a melhor escola de Ribeirão Pires e só interrompe quando digitar Etec MCM
// Autor(a)    : Lucas Prates
// Data atual  : 20/09/2022
Var
esc: caractere

Inicio
repita
escreval ("Qual é a melhor escola de Ribeirão Pires?")
leia(esc)
ate((esc="Etec MCM") ou (esc="ETEC MCM") ou (esc="etec mcm"))

Fimalgoritmo