Algoritmo "tabuada"
// Disciplina   : Programação e Algoritimo
// Professor   : Cintia Pinho
// Descrição   : Imprimir a tabuada
// Autor(a)    : Lucas Prates
// Data atual  : 06/09/2022
Var
n1, cont, resul: inteiro


Inicio
escreval("----Escreval o numero que quer saber a tabuada----")
leia(n1)

para cont de 1 ate 10 faca
       resul <- (n1*cont)
       escreval(n1," X ",cont," = ", resul)
fimpara

Fimalgoritmo