Algoritmo "arearetangulo"
// Professor  : Lucas Ramalho Prates
// Descrissao : solicitar a base e altura e calcular a area do retangulo
// Autor(a) : Nome do(a) aluno(a)
// Data atual : 16/03/2022
Var
base, alt, area: real

Inicio

//entrada
escreval("Digite a base do retangulo aqui: ")
leia(base)
escreval("Digite a altura do retangulo aqui: ")
leia(alt)
limpatela

//processamento
area <- base*alt

//saida
escreval("A area do rtangulo é:", area)

Fimalgoritmo