Algoritmo "areaquadrado"
// Professor  : Lucas Ramalho Prates
// Descrissao : solicitar o lado e calcula a area do quadrado
// Autor(a) : Nome do(a) aluno(a)
// Data atual : 16/03/2022
Var
lado, area: real

Inicio

//entrada
escreval("Digite o lado do quadrado aqui: ")
leia(lado)
limpatela

//processamento
area <- lado^2

//saida
escreval("A area do quadradoo é:", area)

Fimalgoritmo