Algoritmo "mediaaritimedica"
// Professor  : Lucas Ramalho Prates
// Descrissao : fazer a media aritimedica de tres nmeros
// Autor(a) : Nome do(a) aluno(a)
// Data atual : 16/03/2022
Var
n1, n2, n3, media: real

Inicio
escreval("Digite o primeiro numero")
leia(n1)
escreval("Digite o segundo numero")
leia(n2)
escreval("Digite o terceiro numero")
leia(n3)
limpatela

//processamento
media <- (n1+n2+n3)/3

//saida
escreval("A media dos tres numeros é:", media)

Fimalgoritmo